max_retries = 6
exclude_loopback = true
cache = true

base_url = "https://prometheus.github.io"
exclude_path = ["docs/themes"]
exclude = [
  '^https://github\.com/prometheus/client_java/settings',
  '#',
  'CONTRIBUTING.md',
  'LICENSE',
  'MAINTAINERS.md'
]


